### ISSUE TITLE
RABBITMQ_CONFIG_FILE variable set incomaptible.

### ISSUE THREAD

**Issue by cforce** [isindicic/RabbitMqPortable#2]
Server started ... 
"ERROR: Wrong extension for RABBITMQ_CONFIG_FILE: C:\dev\RabbitMqPortable\data\\rabbitmq"
"ERROR: extension should be either .conf or .config"

**Comment by isindicic** [comment]
It seems that your version of RabbitMQ server request that file rabbitmq.config (or rabbitmq.conf) exist in data subdirectory and this is the reason why server isn't started. 

Copy or create those file in C:\dev\RabbitMqPortable\data\ and try again. A sample config file should exist in etc subdirectory.

**Comment by cforce** [comment]
No, that was the case. If i set RABBITMQ_CONFIG_FILE explictly it works .. i would propose your tool needs to do that.

**Comment by isindicic** [comment]
OK.. New [RabbitMqPortable](https://github.com/isindicic/RabbitMqPortable/releases/download/1.0/RabbitMqPortable.zip) now set RABBITMQ_CONFIG_FILE to location described in chapter "Where to put rabbitmq.config file ?" from [main page...](https://github.com/isindicic/RabbitMqPortable)

Hope it will work fine now..

**Comment by subhashsurendran** [comment]
piss poor software
